### PR TITLE
Log CloudFormation stack events on loglevel INFO

### PR DESCRIPTION
**Pull request by sgeb**
Run gradle with `--info` or `-i` to display the CloudFormation stack
events. This is especially helpful for the logfiles in a CI build.

### CODE REVIEW

**Comment by sgeb** [comment]
Hi. Any chance to get this merged and released? Thanks!

**Comment by sgeb** [comment]
Hi @ashlineldridge @neilcampbell. Any chance to get this merged and released?

I'm currently using workarounds in different services to get the functionality of this PR. I'll hold a bit longer but eventually will have to publish a fork of this project in order to get rid of the workarounds. I hope we can keep this plugin in a single project though. Thanks!

**Comment by sgeb** [comment]
@ashlineldridge: great, thanks! 👍

**Comment by ashlineldridge** [comment]
@sgeb, new plugin version available https://plugins.gradle.org/plugin/seek.cloudformation

**Comment by sgeb** [comment]
Thanks for the release, @ashlineldridge. I've bumped to `0.0.27` and removed the workarounds my the CI builds, works as expected, CloudFormation events are printed to the build output.

Re. your review: agree that there's probably a better way to handle the events already seen. I'll put it on my backlog, but realistically won't work on it unless there are issues with the current implementation.

Thanks for your time in releasing the plugin 🎉

**Pull request merged**
